name: pr police ðŸ‘®ðŸ»â€â™‚ï¸

on:
  schedule:
    - cron: '0 9,14 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Clone
        env:
          GIT_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:$GIT_AUTH@github.com/tancor/pr-reviewers-ping.git

      - name: Files
        env:
          PR_POLICE_CONFIG: ${{ secrets.PR_POLICE_CONFIG }}
        run: |
          echo "$PR_POLICE_CONFIG" >> pr-reviewers-ping/pr_reviewers_ping_config.json

      - name: Ping
        working-directory: ./pr-reviewers-ping
        env:
          GIT_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dart pub get
          dart bin/pr_reviewers_ping.dart --token $GIT_AUTH
